[build]
  publish = "public"
  command = "echo 'Static HTML site - no build required'"

[build.environment]
  NODE_VERSION = "18"
  # Disable Python detection
  PYTHON_VERSION = ""
  # Force static site detection
  NPM_FLAGS = "--version"

# Disable Python detection
[build.processing]
  skip_processing = false

# Force static site build
[build.processing.skip]
  python = true

[build.processing.css]
  bundle = false
  minify = false

[build.processing.js]
  bundle = false
  minify = false

[build.processing.html]
  pretty_urls = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
